controller_manager:
  ros__parameters:
    update_rate: 1000
    #use_sim_time: true

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_drive_controller:
  ros__parameters:
    publish_rate: 50.0
    base_frame_id: base_link
    left_wheel_names: ['wheel_left_joint']  # Make sure these names match your URDF or SDF
    right_wheel_names: ['wheel_right_joint']  # Make sure these names match your URDF or SDF
    wheel_separation: 0.4872
    wheel_radius: 0.08
    wheels_per_side: 1
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]
    odom_frame_id: base_footprint
    cmd_vel_timeout: 0.5
    open_loop: true
    tf_frame_prefix_enable: true

    # Wheel separation and radius multipliers
    wheel_separation_multiplier: 1.0 # default: 1.0
    left_wheel_radius_multiplier  : 1.0 # default: 1.0
    right_wheel_radius_multiplier : 1.0 # default: 1.0

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 1.9   # m/s
        has_acceleration_limits: true
        max_acceleration       : 2.0   # m/s^2
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 2.0   # rad/s
        has_acceleration_limits: true
        max_acceleration       : 2.0   # rad/s^2

    use_stamped_vel: false